name: Publish Docker image

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: carlosalm/desafio-rinha-de-backend-2023-q3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker image build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker image
        run: docker image push --all-tags ${{ env.DOCKER_IMAGE_NAME }}
